export const getSpeechRecognitionLang = (language: string): string => {
  const languageMap: Record<string, string> = {
    // Major World Languages
    English: "en-US",
    Spanish: "es-ES",
    French: "fr-FR",
    German: "de-DE",
    Japanese: "ja-JP",
    Italian: "it-IT",
    Portuguese: "pt-BR",
    Russian: "ru-RU",
    "Chinese (Mandarin)": "zh-CN",
    Chinese: "zh-CN", // backwards compatibility
    Korean: "ko-KR",
    Hindi: "hi-IN",
    Arabic: "ar-SA",

    // European Languages
    Dutch: "nl-NL",
    Polish: "pl-PL",
    Swedish: "sv-SE",
    Turkish: "tr-TR",
    Greek: "el-GR",
    Czech: "cs-CZ",
    Finnish: "fi-FI",
    Danish: "da-DK",
    Norwegian: "nb-NO",
    Hungarian: "hu-HU",
    Romanian: "ro-RO",
    Slovak: "sk-SK",
    Ukrainian: "uk-UA",
    Catalan: "ca-ES",
    Bulgarian: "bg-BG",
    Croatian: "hr-HR",
    Serbian: "sr-RS",
    Lithuanian: "lt-LT",
    Latvian: "lv-LV",
    Estonian: "et-EE",
    Slovenian: "sl-SI",
    Icelandic: "is-IS",
    Maltese: "mt-MT",
    Welsh: "cy-GB",
    Irish: "ga-IE",
    Basque: "eu-ES",

    // Asian Languages
    Vietnamese: "vi-VN",
    Thai: "th-TH",
    Indonesian: "id-ID",
    Malay: "ms-MY",
    Filipino: "fil-PH",
    Urdu: "ur-PK",
    Bengali: "bn-BD",
    Telugu: "te-IN",
    Tamil: "ta-IN",
    Marathi: "mr-IN",
    Gujarati: "gu-IN",
    Kannada: "kn-IN",
    Malayalam: "ml-IN",
    Punjabi: "pa-IN",
    Nepali: "ne-NP",
    Sinhala: "si-LK",
    Burmese: "my-MM",
    Khmer: "km-KH",
    Lao: "lo-LA",
    Mongolian: "mn-MN",
    Kazakh: "kk-KZ",
    Uzbek: "uz-UZ",
    Kyrgyz: "ky-KG",
    Tajik: "tg-TJ",
    Azerbaijani: "az-AZ",
    Armenian: "hy-AM",
    Georgian: "ka-GE",

    // Middle Eastern & African Languages
    Hebrew: "he-IL",
    Persian: "fa-IR",
    Kurdish: "ku-TR",
    Amharic: "am-ET",
    Somali: "so-SO",
    Swahili: "sw-KE",
    Yoruba: "yo-NG",
    Igbo: "ig-NG",
    Hausa: "ha-NG",
    Zulu: "zu-ZA",
    Afrikaans: "af-ZA",

    // Other Languages
    Albanian: "sq-AL",
    Bosnian: "bs-BA",
    Macedonian: "mk-MK",
    Montenegrin: "sr-ME",
  };
  return languageMap[language] || "en-US";
};

export const getVoiceForLanguage = (language: string): string => {
  const voiceMap: Record<string, string> = {
    // Major World Languages
    English: "en-US-AriaNeural",
    Spanish: "es-ES-ElviraNeural",
    French: "fr-FR-DeniseNeural",
    German: "de-DE-KatjaNeural",
    Japanese: "ja-JP-NanamiNeural",
    Italian: "it-IT-IsabellaNeural",
    Portuguese: "pt-BR-FranciscaNeural",
    Russian: "ru-RU-SvetlanaNeural",
    "Chinese (Mandarin)": "zh-CN-XiaoxiaoNeural",
    Chinese: "zh-CN-XiaoxiaoNeural", // backwards compatibility
    Korean: "ko-KR-SunHiNeural",
    Hindi: "hi-IN-SwaraNeural",
    Arabic: "ar-SA-ZariyahNeural",

    // European Languages
    Dutch: "nl-NL-ColetteNeural",
    Polish: "pl-PL-AgnieszkaNeural",
    Swedish: "sv-SE-SofieNeural",
    Turkish: "tr-TR-EmelNeural",
    Greek: "el-GR-AthinaNeural",
    Czech: "cs-CZ-VlastaNeural",
    Finnish: "fi-FI-NooraNeural",
    Danish: "da-DK-ChristelNeural",
    Norwegian: "nb-NO-IselinNeural",
    Hungarian: "hu-HU-NoemiNeural",
    Romanian: "ro-RO-AlinaNeural",
    Slovak: "sk-SK-ViktoriaNeural",
    Ukrainian: "uk-UA-PolinaNeural",
    Catalan: "ca-ES-AlbaNeural",
    Bulgarian: "bg-BG-KalinaNeural",
    Croatian: "hr-HR-GabrijelaNeural",
    Serbian: "sr-RS-SophieNeural",
    Lithuanian: "lt-LT-OnaNeural",
    Latvian: "lv-LV-EveritaNeural",
    Estonian: "et-EE-AnuNeural",
    Slovenian: "sl-SI-PetraNeural",
    Icelandic: "is-IS-GudrunNeural",
    Maltese: "mt-MT-GraceNeural",
    Welsh: "cy-GB-NiaNeural",
    Irish: "ga-IE-OrlaNeural",
    Basque: "eu-ES-AinhoaNeural",

    // Asian Languages
    Vietnamese: "vi-VN-HoaiMyNeural",
    Thai: "th-TH-AcharaNeural",
    Indonesian: "id-ID-GadisNeural",
    Malay: "ms-MY-YasminNeural",
    Filipino: "fil-PH-AngeloNeural",
    Urdu: "ur-PK-UzmaNeural",
    Bengali: "bn-BD-NabanitaNeural",
    Telugu: "te-IN-ShrutiNeural",
    Tamil: "ta-IN-PallaviNeural",
    Marathi: "mr-IN-AarohiNeural",
    Gujarati: "gu-IN-DhwaniNeural",
    Kannada: "kn-IN-SapnaNeural",
    Malayalam: "ml-IN-SobhanaNeural",
    Punjabi: "pa-IN-GaganNeural",
    Nepali: "ne-NP-HemkalaNeural",
    Sinhala: "si-LK-ThiliniNeural",
    Burmese: "my-MM-NilarNeural",
    Khmer: "km-KH-PisachNeural",
    Lao: "lo-LA-KeomanyNeural",
    Mongolian: "mn-MN-BataaNeural",
    Kazakh: "kk-KZ-AigulNeural",
    Uzbek: "uz-UZ-MadinaNeural",
    Kyrgyz: "ky-KG-AysulukNeural",
    Tajik: "tg-TJ-AnorNeural",
    Azerbaijani: "az-AZ-BanuNeural",
    Armenian: "hy-AM-AnahitNeural",
    Georgian: "ka-GE-EkaNeural",

    // Middle Eastern & African Languages
    Hebrew: "he-IL-HilaNeural",
    Persian: "fa-IR-DilaraNeural",
    Kurdish: "ku-TR-AranNeural",
    Amharic: "am-ET-MekdesNeural",
    Somali: "so-SO-UbaxNeural",
    Swahili: "sw-KE-ZuriNeural",
    Yoruba: "yo-NG-AkinNeural",
    Igbo: "ig-NG-EbelechukwuNeural",
    Hausa: "ha-NG-AbiolaNeural",
    Zulu: "zu-ZA-ThandiweNeural",
    Afrikaans: "af-ZA-AdriNeural",

    // Other Languages
    Albanian: "sq-AL-AnilaNeural",
    Bosnian: "bs-BA-VesnaNeural",
    Macedonian: "mk-MK-MarijaNeural",
    Montenegrin: "sr-ME-SanjaNeural",
  };
  return voiceMap[language] || "en-US-AriaNeural";
};

export const getLanguagesByRegion = () => {
  return {
    "Major World Languages": [
      "English",
      "Spanish",
      "French",
      "German",
      "Japanese",
      "Italian",
      "Portuguese",
      "Russian",
      "Chinese (Mandarin)",
      "Korean",
      "Hindi",
      "Arabic",
    ],
    "European Languages": [
      "Dutch",
      "Polish",
      "Swedish",
      "Turkish",
      "Greek",
      "Czech",
      "Finnish",
      "Danish",
      "Norwegian",
      "Hungarian",
      "Romanian",
      "Slovak",
      "Ukrainian",
      "Catalan",
      "Bulgarian",
      "Croatian",
      "Serbian",
      "Lithuanian",
      "Latvian",
      "Estonian",
      "Slovenian",
      "Icelandic",
      "Maltese",
      "Welsh",
      "Irish",
      "Basque",
    ],
    "Asian Languages": [
      "Vietnamese",
      "Thai",
      "Indonesian",
      "Malay",
      "Filipino",
      "Urdu",
      "Bengali",
      "Telugu",
      "Tamil",
      "Marathi",
      "Gujarati",
      "Kannada",
      "Malayalam",
      "Punjabi",
      "Nepali",
      "Sinhala",
      "Burmese",
      "Khmer",
      "Lao",
      "Mongolian",
      "Kazakh",
      "Uzbek",
      "Kyrgyz",
      "Tajik",
      "Azerbaijani",
      "Armenian",
      "Georgian",
    ],
    "Middle Eastern & African Languages": [
      "Hebrew",
      "Persian",
      "Kurdish",
      "Amharic",
      "Somali",
      "Swahili",
      "Yoruba",
      "Igbo",
      "Hausa",
      "Zulu",
      "Afrikaans",
    ],
    "Other Languages": ["Albanian", "Bosnian", "Macedonian", "Montenegrin"],
  };
};

export const getLanguageRegion = (language: string): string => {
  const regions = getLanguagesByRegion();
  for (const [region, languages] of Object.entries(regions)) {
    if (languages.includes(language)) {
      return region;
    }
  }
  return "Other Languages";
};
