export const getSpeechRecognitionLang = (language: string): string => {
  const languageMap: Record<string, string> = {
    English: "en-US",
    Spanish: "es-ES",
    French: "fr-FR",
    German: "de-DE",
    Japanese: "ja-JP",
    Italian: "it-IT",
    Portuguese: "pt-BR",
    Russian: "ru-RU",
    Chinese: "zh-CN",
    Korean: "ko-KR",
    Dutch: "nl-NL",
    Hindi: "hi-IN",
    Arabic: "ar-SA",
    Polish: "pl-PL",
    Swedish: "sv-SE",
    Turkish: "tr-TR",
    Vietnamese: "vi-VN",
    Greek: "el-GR",
    Czech: "cs-CZ",
    Finnish: "fi-FI",
    Danish: "da-DK",
    Norwegian: "nb-NO",
    Thai: "th-TH",
    Indonesian: "id-ID",
    Hungarian: "hu-HU",
    Romanian: "ro-RO",
    Slovak: "sk-SK",
    Ukrainian: "uk-UA",
    Catalan: "ca-ES",
    Hebrew: "he-IL",
  };
  return languageMap[language] || "en-US";
};

export const getVoiceForLanguage = (language: string): string => {
  const voiceMap: Record<string, string> = {
    English: "en-US-AriaNeural",
    Spanish: "es-ES-ElviraNeural",
    French: "fr-FR-DeniseNeural",
    German: "de-DE-KatjaNeural",
    Japanese: "ja-JP-NanamiNeural",
    Italian: "it-IT-IsabellaNeural",
    Portuguese: "pt-BR-FranciscaNeural",
    Russian: "ru-RU-SvetlanaNeural",
    Chinese: "zh-CN-XiaoxiaoNeural",
    Korean: "ko-KR-SunHiNeural",
    Dutch: "nl-NL-ColetteNeural",
    Hindi: "hi-IN-SwaraNeural",
    Arabic: "ar-SA-ZariyahNeural",
    Polish: "pl-PL-AgnieszkaNeural",
    Swedish: "sv-SE-SofieNeural",
    Turkish: "tr-TR-EmelNeural",
    Vietnamese: "vi-VN-HoaiMyNeural",
    Greek: "el-GR-AthinaNeural",
    Czech: "cs-CZ-VlastaNeural",
    Finnish: "fi-FI-NooraNeural",
    Danish: "da-DK-ChristelNeural",
    Norwegian: "nb-NO-IselinNeural",
    Thai: "th-TH-AcharaNeural",
    Indonesian: "id-ID-GadisNeural",
    Hungarian: "hu-HU-NoemiNeural",
    Romanian: "ro-RO-AlinaNeural",
    Slovak: "sk-SK-ViktoriaNeural",
    Ukrainian: "uk-UA-PolinaNeural",
    Catalan: "ca-ES-AlbaNeural",
    Hebrew: "he-IL-HilaNeural",
  };
  return voiceMap[language] || "en-US-AriaNeural";
};